### ISSUE TITLE
Some RSpec tests failed

### ISSUE THREAD

**Issue by yui-har** [agileware-jp/redmine_issue_templates#49]
## Summary

RSpec tests using Capybara fail.

## Description

```
% RAILS_ENV=test DRIVER=headless bundle exec rake redmine_issue_templates:spec
...
...

PluginSetting to apply Global issue templates to all the projects
  plugin settings
Capybara starting Puma...
* Version 6.0.2 , codename: Sunflower
* Min threads: 0, max threads: 4
* Listening on http://127.0.0.1:57442
    Settings "apply_global_template_to_all_projects" is displayed. (FAILED - 3)
    Activate "apply_global_template_to_all_projects". (FAILED - 4)
  List global issue templates
    orphaned template loaded (FAILED - 5)

...
...

  3) PluginSetting to apply Global issue templates to all the projects plugin settings  Settings "apply_global_template_to_all_projects" is displayed.
     Failure/Error: log_user(user.login, user.login)

     ArgumentError:
       unknown option: {:capabilities=>[#<Selenium::WebDriver::Remote::Capabilities:0x000000010a445e48 @capabilities={:browser_name=>"chrome", :version=>"", :platform=>:any, :javascript_enabled=>true, :css_selectors_enabled=>true, :takes_screenshot=>false, :native_events=>false, :rotatable=>false, :firefox_profile=>nil, :proxy=>nil, :"goog:chromeOptions"=>{:args=>["window-size=1280,800", "headless", "disable-gpu"]}}>]}
     # ./plugins/redmine_issue_templates/spec/support/login_helper.rb:5:in `log_user'
     # ./plugins/redmine_issue_templates/spec/features/admin_spec.rb:25:in `block (2 levels) in <top (required)>'
     # ./plugins/redmine_issue_templates/lib/tasks/test.rake:27:in `block (2 levels) in <top (required)>'
```

## Environment

- Redmine version : 5.0.3
- Installed plugins : redmine_issue_templates **0.3-stable** (maybe the **master** branch too)
- Ruby version : 3.1.3
- Database : SQLite3

**Comment by zh** [comment]
PR merged to both master and 0.3-stable branches.
