### ISSUE TITLE
Migrate job fails after installing more plugins

### ISSUE THREAD

**Issue by Rocksau80** [agileware-jp/redmine_issue_templates#72]
## Environment
- Redmine version : 5.0.5
- Installed plugins
   additionals
   additional tags
   custom tables
   localizable
   Dashboard 2
   DMSF
   Issues Tree
   Theme changer
   WYSIWYG Editor 
- Ruby version: 3.0.2p107
- OS Platform: Ubuntu 22.04
- Database: MySQL latest version from repository
- Rails Env: Production

## Expected Results
After installing issue templates plugin it should be possible to install other plugins

## Actual Results
It fails with the following output:
== 20230330055341 ChangeGlobalNoteTemplateProjectsTableName: migrating ========
-- rename_table(:global_note_template_projects, :global_note_templates_projects)
rake aborted!
StandardError: An error has occurred, all later migrations canceled:

Mysql2::Error: Table 'global_note_templates_projects' already exists
/var/www/redmine/vendor/bundle/ruby/3.0.0/gems/mysql2-0.5.5/lib/mysql2/client.rb:151:in `_query'
/var/www/redmine/vendor/bundle/ruby/3.0.0/gems/mysql2-0.5.5/lib/mysql2/client.rb:151:in `block in query'
/var/www/redmine/vendor/bundle/ruby/3.0.0/gems/mysql2-0.5.5/lib/mysql2/client.rb:150:in `handle_interrupt'
/var/www/redmine/vendor/bundle/ruby/3.0.0/gems/mysql2-0.5.5/lib/mysql2/client.rb:150:in `query'
/var/www/redmine/vendor/bundle/ruby/3.0.0/gems/activerecord-6.1.7.2/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:206:in `block (2 levels) in execute'
/var/www/redmine/vendor/bundle/ruby/3.0.0/gems/activesupport-6.1.7.2/lib/active_support/dependencies/interlock.rb:48:in `block in permit_concurrent_loads'
/var/www/redmine/vendor/bundle/ruby/3.0.0/gems/activesupport-6.1.7.2/lib/active_support/concurrency/share_lock.rb:187:in `yield_shares'
/var/www/redmine/vendor/bundle/ruby/3.0.0/gems/activesupport-6.1.7.2/lib/active_support/dependencies/interlock.rb:47:in `permit_concurrent_loads'
/var/www/redmine/vendor/bundle/ruby/3.0.0/gems/activerecord-6.1.7.2/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:205:in `block in execute'
/var/www/redmine/vendor/bundle/ruby/3.0.0/gems/activerecord-6.1.7.2/lib/active_record/connection_adapters/abstract_adapter.rb:696:in `block (2 levels) in log'
/var/www/redmine/vendor/bundle/ruby/3.0.0/gems/activesupport-6.1.7.2/lib/active_support/concurrency/load_interlock_aware_monitor.rb:26:in `block (2 levels) in synchronize'
/var/www/redmine/vendor/bundle/ruby/3.0.0/gems/activesupport-6.1.7.2/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `handle_interrupt'
/var/www/redmine/vendor/bundle/ruby/3.0.0/gems/activesupport-6.1.7.2/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `block in synchronize'
/var/www/redmine/vendor/bundle/ruby/3.0.0/gems/activesupport-6.1.7.2/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `handle_interrupt'
/var/www/redmine/vendor/bundle/ruby/3.0.0/gems/activesupport-6.1.7.2/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `synchronize'
/var/www/redmine/vendor/bundle/ruby/3.0.0/gems/activerecord-6.1.7.2/lib/active_record/connection_adapters/abstract_adapter.rb:695:in `block in log'
/var/www/redmine/vendor/bundle/ruby/3.0.0/gems/activesupport-6.1.7.2/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
/var/www/redmine/vendor/bundle/ruby/3.0.0/gems/activerecord-6.1.7.2/lib/active_record/connection_adapters/abstract_adapter.rb:687:in `log'
/var/www/redmine/vendor/bundle/ruby/3.0.0/gems/activerecord-6.1.7.2/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:204:in `execute'
/var/www/redmine/vendor/bundle/ruby/3.0.0/gems/activerecord-6.1.7.2/lib/active_record/connection_adapters/mysql/database_statements.rb:52:in `execute'
/var/www/redmine/vendor/bundle/ruby/3.0.0/gems/activerecord-6.1.7.2/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:315:in `rename_table'
/var/www/redmine/vendor/bundle/ruby/3.0.0/gems/activerecord-6.1.7.2/lib/active_record/migration.rb:929:in `block in method_missing'
/var/www/redmine/vendor/bundle/ruby/3.0.0/gems/activerecord-6.1.7.2/lib/active_record/migration.rb:897:in `block in say_with_time'
/var/www/redmine/vendor/bundle/ruby/3.0.0/gems/activerecord-6.1.7.2/lib/active_record/migration.rb:897:in `say_with_time'
/var/www/redmine/vendor/bundle/ruby/3.0.0/gems/activerecord-6.1.7.2/lib/active_record/migration.rb:918:in `method_missing'
/var/www/redmine/plugins/redmine_issue_templates/db/migrate/20230330055341_change_global_note_template_projects_table_name.rb:3:in `up'
/var/www/redmine/vendor/bundle/ruby/3.0.0/gems/activerecord-6.1.7.2/lib/active_record/migration.rb:870:in `public_send'
/var/www/redmine/vendor/bundle/ruby/3.0.0/gems/activerecord-6.1.7.2/lib/active_record/migration.rb:870:in `exec_migration'
/var/www/redmine/vendor/bundle/ruby/3.0.0/gems/activerecord-6.1.7.2/lib/active_record/migration.rb:851:in `block (2 levels) in migrate'
/var/www/redmine/vendor/bundle/ruby/3.0.0/gems/activerecord-6.1.7.2/lib/active_record/migration.rb:850:in `block in migrate'
/var/www/redmine/vendor/bundle/ruby/3.0.0/gems/activerecord-6.1.7.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:462:in `with_connection'
/var/www/redmine/vendor/bundle/ruby/3.0.0/gems/activerecord-6.1.7.2/lib/active_record/migration.rb:849:in `migrate'
/var/www/redmine/vendor/bundle/ruby/3.0.0/gems/activerecord-6.1.7.2/lib/active_record/migration.rb:1037:in `migrate'
/var/www/redmine/vendor/bundle/ruby/3.0.0/gems/activerecord-6.1.7.2/lib/active_record/migration.rb:1329:in `block in execute_migration_in_transaction'
/var/www/redmine/vendor/bundle/ruby/3.0.0/gems/activerecord-6.1.7.2/lib/active_record/migration.rb:1382:in `ddl_transaction'
/var/www/redmine/vendor/bundle/ruby/3.0.0/gems/activerecord-6.1.7.2/lib/active_record/migration.rb:1328:in `execute_migration_in_transaction'
/var/www/redmine/vendor/bundle/ruby/3.0.0/gems/activerecord-6.1.7.2/lib/active_record/migration.rb:1302:in `each'
/var/www/redmine/vendor/bundle/ruby/3.0.0/gems/activerecord-6.1.7.2/lib/active_record/migration.rb:1302:in `migrate_without_lock'
/var/www/redmine/vendor/bundle/ruby/3.0.0/gems/activerecord-6.1.7.2/lib/active_record/migration.rb:1251:in `block in migrate'
/var/www/redmine/vendor/bundle/ruby/3.0.0/gems/activerecord-6.1.7.2/lib/active_record/migration.rb:1401:in `block in with_advisory_lock'
/var/www/redmine/vendor/bundle/ruby/3.0.0/gems/activerecord-6.1.7.2/lib/active_record/migration.rb:1416:in `block in with_advisory_lock_connection'
/var/www/redmine/vendor/bundle/ruby/3.0.0/gems/activerecord-6.1.7.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:462:in `with_connection'
/var/www/redmine/vendor/bundle/ruby/3.0.0/gems/activerecord-6.1.7.2/lib/active_record/migration.rb:1416:in `with_advisory_lock_connection'
/var/www/redmine/vendor/bundle/ruby/3.0.0/gems/activerecord-6.1.7.2/lib/active_record/migration.rb:1397:in `with_advisory_lock'
/var/www/redmine/vendor/bundle/ruby/3.0.0/gems/activerecord-6.1.7.2/lib/active_record/migration.rb:1251:in `migrate'
/var/www/redmine/lib/redmine/plugin.rb:468:in `up'
/var/www/redmine/vendor/bundle/ruby/3.0.0/gems/activerecord-6.1.7.2/lib/active_record/migration.rb:1061:in `migrate'
/var/www/redmine/lib/redmine/plugin.rb:500:in `migrate_plugin'
/var/www/redmine/lib/redmine/plugin.rb:441:in `migrate'
/var/www/redmine/lib/redmine/plugin.rb:455:in `block in migrate'
/var/www/redmine/lib/redmine/plugin.rb:454:in `each'
/var/www/redmine/lib/redmine/plugin.rb:454:in `migrate'
/var/www/redmine/lib/tasks/redmine.rake:151:in `block (3 levels) in <top (required)>'
/var/www/redmine/vendor/bundle/ruby/3.0.0/gems/rake-13.0.6/exe/rake:27:in `<top (required)>'

Caused by:
ActiveRecord::StatementInvalid: Mysql2::Error: Table 'global_note_templates_projects' already exists
/var/www/redmine/vendor/bundle/ruby/3.0.0/gems/mysql2-0.5.5/lib/mysql2/client.rb:151:in `_query'
/var/www/redmine/vendor/bundle/ruby/3.0.0/gems/mysql2-0.5.5/lib/mysql2/client.rb:151:in `block in query'
/var/www/redmine/vendor/bundle/ruby/3.0.0/gems/mysql2-0.5.5/lib/mysql2/client.rb:150:in `handle_interrupt'
/var/www/redmine/vendor/bundle/ruby/3.0.0/gems/mysql2-0.5.5/lib/mysql2/client.rb:150:in `query'
/var/www/redmine/vendor/bundle/ruby/3.0.0/gems/activerecord-6.1.7.2/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:206:in `block (2 levels) in execute'
/var/www/redmine/vendor/bundle/ruby/3.0.0/gems/activesupport-6.1.7.2/lib/active_support/dependencies/interlock.rb:48:in `block in permit_concurrent_loads'
/var/www/redmine/vendor/bundle/ruby/3.0.0/gems/activesupport-6.1.7.2/lib/active_support/concurrency/share_lock.rb:187:in `yield_shares'
/var/www/redmine/vendor/bundle/ruby/3.0.0/gems/activesupport-6.1.7.2/lib/active_support/dependencies/interlock.rb:47:in `permit_concurrent_loads'
/var/www/redmine/vendor/bundle/ruby/3.0.0/gems/activerecord-6.1.7.2/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:205:in `block in execute'
/var/www/redmine/vendor/bundle/ruby/3.0.0/gems/activerecord-6.1.7.2/lib/active_record/connection_adapters/abstract_adapter.rb:696:in `block (2 levels) in log'
/var/www/redmine/vendor/bundle/ruby/3.0.0/gems/activesupport-6.1.7.2/lib/active_support/concurrency/load_interlock_aware_monitor.rb:26:in `block (2 levels) in synchronize'
/var/www/redmine/vendor/bundle/ruby/3.0.0/gems/activesupport-6.1.7.2/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `handle_interrupt'
/var/www/redmine/vendor/bundle/ruby/3.0.0/gems/activesupport-6.1.7.2/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `block in synchronize'
/var/www/redmine/vendor/bundle/ruby/3.0.0/gems/activesupport-6.1.7.2/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `handle_interrupt'
/var/www/redmine/vendor/bundle/ruby/3.0.0/gems/activesupport-6.1.7.2/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `synchronize'
/var/www/redmine/vendor/bundle/ruby/3.0.0/gems/activerecord-6.1.7.2/lib/active_record/connection_adapters/abstract_adapter.rb:695:in `block in log'
/var/www/redmine/vendor/bundle/ruby/3.0.0/gems/activesupport-6.1.7.2/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
/var/www/redmine/vendor/bundle/ruby/3.0.0/gems/activerecord-6.1.7.2/lib/active_record/connection_adapters/abstract_adapter.rb:687:in `log'
/var/www/redmine/vendor/bundle/ruby/3.0.0/gems/activerecord-6.1.7.2/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:204:in `execute'
/var/www/redmine/vendor/bundle/ruby/3.0.0/gems/activerecord-6.1.7.2/lib/active_record/connection_adapters/mysql/database_statements.rb:52:in `execute'
/var/www/redmine/vendor/bundle/ruby/3.0.0/gems/activerecord-6.1.7.2/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:315:in `rename_table'
/var/www/redmine/vendor/bundle/ruby/3.0.0/gems/activerecord-6.1.7.2/lib/active_record/migration.rb:929:in `block in method_missing'
/var/www/redmine/vendor/bundle/ruby/3.0.0/gems/activerecord-6.1.7.2/lib/active_record/migration.rb:897:in `block in say_with_time'
/var/www/redmine/vendor/bundle/ruby/3.0.0/gems/activerecord-6.1.7.2/lib/active_record/migration.rb:897:in `say_with_time'
/var/www/redmine/vendor/bundle/ruby/3.0.0/gems/activerecord-6.1.7.2/lib/active_record/migration.rb:918:in `method_missing'
/var/www/redmine/plugins/redmine_issue_templates/db/migrate/20230330055341_change_global_note_template_projects_table_name.rb:3:in `up'
/var/www/redmine/vendor/bundle/ruby/3.0.0/gems/activerecord-6.1.7.2/lib/active_record/migration.rb:870:in `public_send'
/var/www/redmine/vendor/bundle/ruby/3.0.0/gems/activerecord-6.1.7.2/lib/active_record/migration.rb:870:in `exec_migration'
/var/www/redmine/vendor/bundle/ruby/3.0.0/gems/activerecord-6.1.7.2/lib/active_record/migration.rb:851:in `block (2 levels) in migrate'
/var/www/redmine/vendor/bundle/ruby/3.0.0/gems/activerecord-6.1.7.2/lib/active_record/migration.rb:850:in `block in migrate'
/var/www/redmine/vendor/bundle/ruby/3.0.0/gems/activerecord-6.1.7.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:462:in `with_connection'
/var/www/redmine/vendor/bundle/ruby/3.0.0/gems/activerecord-6.1.7.2/lib/active_record/migration.rb:849:in `migrate'
/var/www/redmine/vendor/bundle/ruby/3.0.0/gems/activerecord-6.1.7.2/lib/active_record/migration.rb:1037:in `migrate'
/var/www/redmine/vendor/bundle/ruby/3.0.0/gems/activerecord-6.1.7.2/lib/active_record/migration.rb:1329:in `block in execute_migration_in_transaction'
/var/www/redmine/vendor/bundle/ruby/3.0.0/gems/activerecord-6.1.7.2/lib/active_record/migration.rb:1382:in `ddl_transaction'
/var/www/redmine/vendor/bundle/ruby/3.0.0/gems/activerecord-6.1.7.2/lib/active_record/migration.rb:1328:in `execute_migration_in_transaction'
/var/www/redmine/vendor/bundle/ruby/3.0.0/gems/activerecord-6.1.7.2/lib/active_record/migration.rb:1302:in `each'
/var/www/redmine/vendor/bundle/ruby/3.0.0/gems/activerecord-6.1.7.2/lib/active_record/migration.rb:1302:in `migrate_without_lock'
/var/www/redmine/vendor/bundle/ruby/3.0.0/gems/activerecord-6.1.7.2/lib/active_record/migration.rb:1251:in `block in migrate'
/var/www/redmine/vendor/bundle/ruby/3.0.0/gems/activerecord-6.1.7.2/lib/active_record/migration.rb:1401:in `block in with_advisory_lock'
/var/www/redmine/vendor/bundle/ruby/3.0.0/gems/activerecord-6.1.7.2/lib/active_record/migration.rb:1416:in `block in with_advisory_lock_connection'
/var/www/redmine/vendor/bundle/ruby/3.0.0/gems/activerecord-6.1.7.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:462:in `with_connection'
/var/www/redmine/vendor/bundle/ruby/3.0.0/gems/activerecord-6.1.7.2/lib/active_record/migration.rb:1416:in `with_advisory_lock_connection'
/var/www/redmine/vendor/bundle/ruby/3.0.0/gems/activerecord-6.1.7.2/lib/active_record/migration.rb:1397:in `with_advisory_lock'
/var/www/redmine/vendor/bundle/ruby/3.0.0/gems/activerecord-6.1.7.2/lib/active_record/migration.rb:1251:in `migrate'
/var/www/redmine/lib/redmine/plugin.rb:468:in `up'
/var/www/redmine/vendor/bundle/ruby/3.0.0/gems/activerecord-6.1.7.2/lib/active_record/migration.rb:1061:in `migrate'
/var/www/redmine/lib/redmine/plugin.rb:500:in `migrate_plugin'
/var/www/redmine/lib/redmine/plugin.rb:441:in `migrate'
/var/www/redmine/lib/redmine/plugin.rb:455:in `block in migrate'
/var/www/redmine/lib/redmine/plugin.rb:454:in `each'
/var/www/redmine/lib/redmine/plugin.rb:454:in `migrate'
/var/www/redmine/lib/tasks/redmine.rake:151:in `block (3 levels) in <top (required)>'
/var/www/redmine/vendor/bundle/ruby/3.0.0/gems/rake-13.0.6/exe/rake:27:in `<top (required)>'

Caused by:
Mysql2::Error: Table 'global_note_templates_projects' already exists
/var/www/redmine/vendor/bundle/ruby/3.0.0/gems/mysql2-0.5.5/lib/mysql2/client.rb:151:in `_query'
/var/www/redmine/vendor/bundle/ruby/3.0.0/gems/mysql2-0.5.5/lib/mysql2/client.rb:151:in `block in query'
/var/www/redmine/vendor/bundle/ruby/3.0.0/gems/mysql2-0.5.5/lib/mysql2/client.rb:150:in `handle_interrupt'
/var/www/redmine/vendor/bundle/ruby/3.0.0/gems/mysql2-0.5.5/lib/mysql2/client.rb:150:in `query'
/var/www/redmine/vendor/bundle/ruby/3.0.0/gems/activerecord-6.1.7.2/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:206:in `block (2 levels) in execute'
/var/www/redmine/vendor/bundle/ruby/3.0.0/gems/activesupport-6.1.7.2/lib/active_support/dependencies/interlock.rb:48:in `block in permit_concurrent_loads'
/var/www/redmine/vendor/bundle/ruby/3.0.0/gems/activesupport-6.1.7.2/lib/active_support/concurrency/share_lock.rb:187:in `yield_shares'
/var/www/redmine/vendor/bundle/ruby/3.0.0/gems/activesupport-6.1.7.2/lib/active_support/dependencies/interlock.rb:47:in `permit_concurrent_loads'
/var/www/redmine/vendor/bundle/ruby/3.0.0/gems/activerecord-6.1.7.2/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:205:in `block in execute'
/var/www/redmine/vendor/bundle/ruby/3.0.0/gems/activerecord-6.1.7.2/lib/active_record/connection_adapters/abstract_adapter.rb:696:in `block (2 levels) in log'
/var/www/redmine/vendor/bundle/ruby/3.0.0/gems/activesupport-6.1.7.2/lib/active_support/concurrency/load_interlock_aware_monitor.rb:26:in `block (2 levels) in synchronize'
/var/www/redmine/vendor/bundle/ruby/3.0.0/gems/activesupport-6.1.7.2/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `handle_interrupt'
/var/www/redmine/vendor/bundle/ruby/3.0.0/gems/activesupport-6.1.7.2/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `block in synchronize'
/var/www/redmine/vendor/bundle/ruby/3.0.0/gems/activesupport-6.1.7.2/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `handle_interrupt'
/var/www/redmine/vendor/bundle/ruby/3.0.0/gems/activesupport-6.1.7.2/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `synchronize'
/var/www/redmine/vendor/bundle/ruby/3.0.0/gems/activerecord-6.1.7.2/lib/active_record/connection_adapters/abstract_adapter.rb:695:in `block in log'
/var/www/redmine/vendor/bundle/ruby/3.0.0/gems/activesupport-6.1.7.2/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
/var/www/redmine/vendor/bundle/ruby/3.0.0/gems/activerecord-6.1.7.2/lib/active_record/connection_adapters/abstract_adapter.rb:687:in `log'
/var/www/redmine/vendor/bundle/ruby/3.0.0/gems/activerecord-6.1.7.2/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:204:in `execute'
/var/www/redmine/vendor/bundle/ruby/3.0.0/gems/activerecord-6.1.7.2/lib/active_record/connection_adapters/mysql/database_statements.rb:52:in `execute'
/var/www/redmine/vendor/bundle/ruby/3.0.0/gems/activerecord-6.1.7.2/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:315:in `rename_table'
/var/www/redmine/vendor/bundle/ruby/3.0.0/gems/activerecord-6.1.7.2/lib/active_record/migration.rb:929:in `block in method_missing'
/var/www/redmine/vendor/bundle/ruby/3.0.0/gems/activerecord-6.1.7.2/lib/active_record/migration.rb:897:in `block in say_with_time'
/var/www/redmine/vendor/bundle/ruby/3.0.0/gems/activerecord-6.1.7.2/lib/active_record/migration.rb:897:in `say_with_time'
/var/www/redmine/vendor/bundle/ruby/3.0.0/gems/activerecord-6.1.7.2/lib/active_record/migration.rb:918:in `method_missing'
/var/www/redmine/plugins/redmine_issue_templates/db/migrate/20230330055341_change_global_note_template_projects_table_name.rb:3:in `up'
/var/www/redmine/vendor/bundle/ruby/3.0.0/gems/activerecord-6.1.7.2/lib/active_record/migration.rb:870:in `public_send'
/var/www/redmine/vendor/bundle/ruby/3.0.0/gems/activerecord-6.1.7.2/lib/active_record/migration.rb:870:in `exec_migration'
/var/www/redmine/vendor/bundle/ruby/3.0.0/gems/activerecord-6.1.7.2/lib/active_record/migration.rb:851:in `block (2 levels) in migrate'
/var/www/redmine/vendor/bundle/ruby/3.0.0/gems/activerecord-6.1.7.2/lib/active_record/migration.rb:850:in `block in migrate'
/var/www/redmine/vendor/bundle/ruby/3.0.0/gems/activerecord-6.1.7.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:462:in `with_connection'
/var/www/redmine/vendor/bundle/ruby/3.0.0/gems/activerecord-6.1.7.2/lib/active_record/migration.rb:849:in `migrate'
/var/www/redmine/vendor/bundle/ruby/3.0.0/gems/activerecord-6.1.7.2/lib/active_record/migration.rb:1037:in `migrate'
/var/www/redmine/vendor/bundle/ruby/3.0.0/gems/activerecord-6.1.7.2/lib/active_record/migration.rb:1329:in `block in execute_migration_in_transaction'
/var/www/redmine/vendor/bundle/ruby/3.0.0/gems/activerecord-6.1.7.2/lib/active_record/migration.rb:1382:in `ddl_transaction'
/var/www/redmine/vendor/bundle/ruby/3.0.0/gems/activerecord-6.1.7.2/lib/active_record/migration.rb:1328:in `execute_migration_in_transaction'
/var/www/redmine/vendor/bundle/ruby/3.0.0/gems/activerecord-6.1.7.2/lib/active_record/migration.rb:1302:in `each'
/var/www/redmine/vendor/bundle/ruby/3.0.0/gems/activerecord-6.1.7.2/lib/active_record/migration.rb:1302:in `migrate_without_lock'
/var/www/redmine/vendor/bundle/ruby/3.0.0/gems/activerecord-6.1.7.2/lib/active_record/migration.rb:1251:in `block in migrate'
/var/www/redmine/vendor/bundle/ruby/3.0.0/gems/activerecord-6.1.7.2/lib/active_record/migration.rb:1401:in `block in with_advisory_lock'
/var/www/redmine/vendor/bundle/ruby/3.0.0/gems/activerecord-6.1.7.2/lib/active_record/migration.rb:1416:in `block in with_advisory_lock_connection'
/var/www/redmine/vendor/bundle/ruby/3.0.0/gems/activerecord-6.1.7.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:462:in `with_connection'
/var/www/redmine/vendor/bundle/ruby/3.0.0/gems/activerecord-6.1.7.2/lib/active_record/migration.rb:1416:in `with_advisory_lock_connection'
/var/www/redmine/vendor/bundle/ruby/3.0.0/gems/activerecord-6.1.7.2/lib/active_record/migration.rb:1397:in `with_advisory_lock'
/var/www/redmine/vendor/bundle/ruby/3.0.0/gems/activerecord-6.1.7.2/lib/active_record/migration.rb:1251:in `migrate'
/var/www/redmine/lib/redmine/plugin.rb:468:in `up'
/var/www/redmine/vendor/bundle/ruby/3.0.0/gems/activerecord-6.1.7.2/lib/active_record/migration.rb:1061:in `migrate'
/var/www/redmine/lib/redmine/plugin.rb:500:in `migrate_plugin'
/var/www/redmine/lib/redmine/plugin.rb:441:in `migrate'
/var/www/redmine/lib/redmine/plugin.rb:455:in `block in migrate'
/var/www/redmine/lib/redmine/plugin.rb:454:in `each'
/var/www/redmine/lib/redmine/plugin.rb:454:in `migrate'
/var/www/redmine/lib/tasks/redmine.rake:151:in `block (3 levels) in <top (required)>'
/var/www/redmine/vendor/bundle/ruby/3.0.0/gems/rake-13.0.6/exe/rake:27:in `<top (required)>'
Tasks: TOP => redmine:plugins:migrate

**Comment by Rocksau80** [comment]
I'd say it is related to the commit for #65 . I'm now using a version before that change and it works.
